### ISSUE TITLE
Create a libraries.io blog?

### ISSUE THREAD

**Issue by orta** [librariesio/supporters#23]
Hey all, I see things like this:

https://twitter.com/teabass/status/841350906155266050
https://twitter.com/teabass/status/842149968794259457

and I'm really interested in knowing more about these kind of events and how people are using libraries.io - IMO they'd make great blog posts

In [CocoaPods](http://blog.cocoapods.org/archives/) we do aim to do blog posts for major events, meetups and major releases (basically anything non-transitory) - it might do y'all well to have something similar

**Comment by andrew** [comment]
@orta I've just made a medium "publication" to group all the libraries related blog posts @BenJam and I have done: https://medium.com/libraries-io

**Comment by BenJam** [comment]
I support this message. Also: we've kind of agreed that, until Libraries.io is its own legal entity, we should probably continue to blog personally about the project. Okay to close?

**Comment by orta** [comment]
Sounds legit 👍
