### ISSUE TITLE
Add support for GitLab and BitBucket users

### ISSUE THREAD

**Issue by BenJam** [librariesio/supporters#6]
To add support for users of GitLab and BitBucket to 

- [x] use their accounts on these services to authenticate on libraries.io
- [x] view, monitor and otherwise interact with repositories hosted on GitLab or BitBucket.

**Comment by BenJam** [comment]
This is not yet clsoed as there's still some work to tie up

- [ ] add owner information to a project when the owner is a GitLab or BitBucket user.

**Comment by andrew** [comment]
@BenJam there's a few more bits still to add: https://github.com/librariesio/libraries.io/pull/1152#issuecomment-279992059
