### ISSUE TITLE
Release dependency graph and metric data under a permissive licence.

### ISSUE THREAD

**Issue by BenJam** [librariesio/supporters#9]
Specifically one which can be used by the scientific and research communities.

- [x] define requirements for a licence
- [x] explore available licences
- [x] decide on a licence
- [x] decide on formats
- [x] register doi https://www.crossref.org/services/content-registration/
- [x] release data

**Comment by BenJam** [comment]
Will lean on our advisor @ldodds regarding licence. @andrew and I have spoken about using an equivalent of AGPL for data or, in fact, using AGPL for the data.

**Comment by andrew** [comment]
Related issue: https://github.com/librariesio/libraries.io/issues/609

**Comment by ldodds** [comment]
But AGPL isn't really suitable for data as it doesn't address the variety of database rights that you or others may have in the data, better to use a licence that's designed for data. In general I think an AGPL type provision would be a non-starter for data: it would make it impossible to mix the data with other sensitive (e.g. personal) data without requiring that to be released, which wouldn't be legal.

We should have a chat about the options :)

**Comment by BenJam** [comment]
> We should have a chat about the options :)

^ this.

**Comment by ldodds** [comment]
@BenJam @andrew shall we grab a coffee sometime soon to discuss licensing options, etc? I'm happy to take an action from that to write-up and publish notes here so others can add their comments :)

**Comment by BenJam** [comment]
Sure, let us know next time you’re in town. Apologies that this hasn’t come to you sooner, I’m focussing on the sustainability plan (#15) atm.

**Comment by ldodds** [comment]
I'm around Friday morning, if that works?

**Comment by BenJam** [comment]
Just to summarise the above conversation: There's a movement to release data under a public domain licence but a CC-BY-SA licence would allow the federation of data and derivatives by researchers and a papers alike so long as the source is attributed. Having checked with a a couple of potential users this does not seem to be a general issue so the current decision is to go with CC-BY-SA.

**Comment by BenJam** [comment]
In order to test the formats we have released information to Uni. Mons.

**Comment by BenJam** [comment]
So thoughts for this at the moment are: 

We should use this as an opportunity to move a lot of the 'experiments' (unseen infrastructure, bus factor et al) into a separate /experiments page on libraries.io and use that as the main push into the data. The classic 'if you found this interesting go nuts yourself' play. Having another, versioned data.libraries.io subdomain is definitely a benefit and make it easier to manage data-based stuff separate from the service/application side though.

**Comment by BenJam** [comment]
note too that feedback on formats was positive 👍

**Comment by BenJam** [comment]
Following good chat with @arfon:

- AWS have a public dataset programme https://aws.amazon.com/public-datasets/
- Zenodo.org may be a good solution for storing/updating static releases. 
- James might be worth a prod once the data is up http://herbsleb.org/ 

prioritising this for release in June, prior to events in SFO/NY.

**Comment by andrew** [comment]
Open Data ship list over here: https://github.com/librariesio/libraries.io/issues/1483

**Comment by andrew** [comment]
🚢
